version: '3.8'
services:
  scraper:
    build: .
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=coronavirus
      - RESET_DB=true
    depends_on:
      db:
       condition: service_healthy
    volumes:
      - ./cache:/cache
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coronavirus
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db:
    driver: local
  scraper:
    driver: local